"""requisites

Revision ID: 07148d64f306
Revises: ea9d27268d01
Create Date: 2023-07-26 11:47:50.360092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07148d64f306'
down_revision = 'ea9d27268d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisites',
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('platform_id', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.token'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number')
    )
    op.create_unique_constraint(None, 'wallets', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_table('requisites')
    # ### end Alembic commands ###
