"""requisites

Revision ID: 1a373bb3cfdf
Revises: 963974c40814
Create Date: 2023-07-26 11:50:44.116401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a373bb3cfdf'
down_revision = '963974c40814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisites', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisites', 'is_hidden')
    # ### end Alembic commands ###
