"""accounts

Revision ID: 52f6cc1cdc07
Revises: 5748fd0b5bc6
Create Date: 2023-07-25 10:17:38.021211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f6cc1cdc07'
down_revision = '5748fd0b5bc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'currency')
    op.drop_column('platforms', 'is_active')
    op.drop_column('platforms', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('platforms', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('platforms', sa.Column('currency', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
