"""accounts

Revision ID: 5748fd0b5bc6
Revises: eb6cae1dbd02
Create Date: 2023-07-25 09:30:15.384507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5748fd0b5bc6'
down_revision = 'eb6cae1dbd02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('balance', sa.Float(), nullable=False))
    op.add_column('platforms', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('platforms', sa.Column('currency', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'platforms', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_column('platforms', 'currency')
    op.drop_column('platforms', 'is_active')
    op.drop_column('platforms', 'balance')
    # ### end Alembic commands ###
