"""requisites

Revision ID: 963974c40814
Revises: 07148d64f306
Create Date: 2023-07-26 11:49:44.826505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963974c40814'
down_revision = '07148d64f306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisites', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'requisites', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requisites', type_='unique')
    op.drop_column('requisites', 'is_active')
    # ### end Alembic commands ###
