"""accounts

Revision ID: eb6cae1dbd02
Revises: 3bd20b3d4c7f
Create Date: 2023-07-24 13:26:57.923825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6cae1dbd02'
down_revision = '3bd20b3d4c7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('token')
    )
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.UniqueConstraint('token', name='accounts_token_key')
    )
    op.drop_table('platforms')
    # ### end Alembic commands ###
